# Module 2: Exercise

>__Task 1__
>
>Import pandas and NumPy libraries using their alias

In [2]:
import pandas as pd
import numpy as np

## Python Native Data Types

### Numbers, Strings, Booleans

>__Task 2__
>
>Perform the following operations and return to see the results
>- $3+2\times4$
>- $(3+2)\div4$
>- $(3+2)^4$
>- get the integer quotient of $(3+2)/4$ using floor division

In [3]:
3+2*4

11

In [4]:
(3+2)/4

1.25

In [7]:
(3+2)**4

625

In [6]:
(3+2)//4

1

Note __the floor division rounds the result to the nearest whole number__.

>__Task 3__
>
>Run the following cells and find the data type of each object

In [8]:
4//7

0

In [9]:
# Return data type
type(4//7)

int

In [13]:
a = 11/(-3)
a


-3.6666666666666665

In [12]:
# Return data type
type(a)

float

In [16]:
b = True
# Return data type
type(b)

bool

>__Task 4__
>
>Assume your student ID is 00223298, assign it to a variable as a string object

In [18]:
id = '00224398'
type(id)


str

>__Task 5__
>
>Convert the variable __c__ below to float

In [22]:
c = '6.0'
# Convert to float
c = float(c)
c

6.0

In [23]:
# Return data type
type(c)

float

>__Task 6__
>
>Run the cell below to get the value of variable __d__ and then convert it to integer

In [24]:
d = (-6) < 78
d

True

In [25]:
# Convert to integer
d = int(d)
d

1

In [26]:
# Return data type
type(d)

int

### Lists, Tuples, Sets

>__Task 7__
>
>Create a list, a tuple, and a set containing the following elements and compare the outputs:
>
>`0`, `robot` (str), `-9`, `False` (bool), `77`, `77`, `100`, `true` (str)

In [33]:
# Create a list
l = [0,'robot',-9,False, 77,77,100, 'true']
l

[0, 'robot', -9, False, 77, 77, 100, 'true']

In [34]:
# Return data type
type(l)

list

In [35]:
# Create a tuple
t = (0,'robot',-9,False, 77,77,100, 'true')

In [36]:
# Return data type
type(t)

tuple

In [37]:
# Create a set
s = {0,'robot',-9,False, 77,77,100, 'true'}
s

{-9, 0, 100, 77, 'robot', 'true'}

In [38]:
# Return data type
type(s)

set

>__Task 8__
>
>Overwrite the element `true` to `1` in the above list __l__

In [48]:
l[7] = 1
l

[0, 'robot', -9, False, 77, 77, 100, 1]

>__Task 9__
>
>Add `age` and `weight` to the list __e__ below using __`+`__

In [50]:
e = ['diabetes', 'heart bypass']
e = e + ['age', 'weight']
e

['diabetes', 'heart bypass', 'age', 'weight']

In [53]:
f =  e + ['age', 'weight']
f

['diabetes',
 'heart bypass',
 'age',
 'weight',
 'age',
 'weight',
 'age',
 'weight',
 'age',
 'weight']

Alternatively, you can use the __`extend()`__ method to add item(s) to the end of the list:

In [52]:
e.extend(['age', 'weight'])
e

['diabetes', 'heart bypass', 'age', 'weight', 'age', 'weight', 'age', 'weight']

### Dictionaries

In [54]:
cities = {'Australia' :['Sydney', 'Melbourne', 'Canberra'],
          'Canada'    :['Toronto', 'Montreal', 'Ottawa'],
          'Germany'   :['Berlin', 'Hamburg', 'Munich'],
          'Japan'     :['Tokyo', 'Osaka', 'Nagoya']}
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Germany': ['Berlin', 'Hamburg', 'Munich'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya']}

>__Task 10__
>
>Return only values of the `Japan` key

In [55]:
cities['Japan']

['Tokyo', 'Osaka', 'Nagoya']

>__Task 11__
>
>Return only values and only keys of the dictionary __cities__

In [56]:
# Return only values
cities.values()

dict_values([['Sydney', 'Melbourne', 'Canberra'], ['Toronto', 'Montreal', 'Ottawa'], ['Berlin', 'Hamburg', 'Munich'], ['Tokyo', 'Osaka', 'Nagoya']])

In [57]:
# Return only keys
cities.keys()

dict_keys(['Australia', 'Canada', 'Germany', 'Japan'])

You can use a __`for`__ loop to print not only keys but also the values corresponding to that keys:

In [58]:
for k in cities.keys():
    print('key: ', k, '\nvalue: ', cities[k], '\n')

key:  Australia 
value:  ['Sydney', 'Melbourne', 'Canberra'] 

key:  Canada 
value:  ['Toronto', 'Montreal', 'Ottawa'] 

key:  Germany 
value:  ['Berlin', 'Hamburg', 'Munich'] 

key:  Japan 
value:  ['Tokyo', 'Osaka', 'Nagoya'] 



>__Task 12__
>
>Return the same output above using the __`items()`__ method within a `for` loop

In [78]:
for i, j in cities.items():
    print(f'key:  {i} \nvalue:  {j}')

key:  Australia 
value:  ['Sydney', 'Melbourne', 'Canberra']
key:  Canada 
value:  ['Toronto', 'Montreal', 'Ottawa']
key:  Germany 
value:  ['Berlin', 'Hamburg', 'Munich']
key:  Japan 
value:  ['Tokyo', 'Osaka', 'Nagoya']


>__Task 13__
>
>Add `Egypt` as a new key to __cities__ and `Cairo`, `Durban`, `Alexandria` as its corresponding values

In [85]:
cities['Egypt'] = ['Cairo', 'Durban', 'Alexandria']
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Germany': ['Berlin', 'Hamburg', 'Munich'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya'],
 'Egypt': ['Cairo', 'Durban', 'Alexandria']}

>__Task 14__
>
>`Durban` is actually in South Africa. Overwrite it with `Giza` and then confirm values of the __Egypt__ column

In [96]:
cities['Egypt'][1] = 'Giza'
cities

{'Australia': ['Sydney', 'Melbourne', 'Canberra'],
 'Canada': ['Toronto', 'Montreal', 'Ottawa'],
 'Germany': ['Berlin', 'Hamburg', 'Munich'],
 'Japan': ['Tokyo', 'Osaka', 'Nagoya'],
 'Egypt': ['Cairo', 'Giza', 'Alexandria']}

>__Task 15__
>
>Delete the key `Germany` from __cities__ 

In [102]:
new_cities = cities.pop('Germany')
# we can also use del cities['Germany']


KeyError: 'Germany'

In [105]:
cities
new_cities

['Berlin', 'Hamburg', 'Munich']

## NumPy Arrays

>__Task 16__
>
>Create an array that contains a list of `99`, `2`, `65`

In [111]:
li = [99,2,65]
arr = np.array(li)
arr

array([99,  2, 65])

>__Task 17__
>
>Run the following operations to see the results

In [112]:
# Natural logarithm
np.log(arr)

array([4.59511985, 0.69314718, 4.17438727])

In [113]:
# Square root
np.sqrt(arr)

array([9.94987437, 1.41421356, 8.06225775])

In [114]:
# Cosine
np.cos(arr)

array([ 0.03982088, -0.41614684, -0.56245385])

We can use the __`arange()`__ method to create an array from 0 to any number of values we want. For example, we want an array of 20 numbers, we write:

In [115]:
num1 = np.arange(20)
num1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

>__Task 18__
>
>Retrieve the first 5 numbers of the above array __num1__

In [121]:
num1[0:5]

array([0, 1, 2, 3, 4])

We can also pass the __`reshape()`__ function with `arange()` to specify rows and columns. For example, we can rearrange the above array into 5 rows and 4 columns:

In [122]:
num2 = np.arange(20).reshape(5,4)
num2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

>__Task 19__
>
>Retrieve the numbers from the last 2 rows and first 3 columns in the array __num2__ (your output should return `[12, 13, 14], [16, 17, 18]`)

In [141]:
num2[ 3:,:3]

array([[12, 13, 14],
       [16, 17, 18]])

## Pandas Series and DataFrames

>__Task 20__
>
>Import the data file "bank_data.csv"

In [142]:
bank = pd.read_csv("./raw/bank_data.csv")
bank

age            job  marital  education default  balance housing loan  \
0     30.0     unemployed  married    primary      no   1787.0      no   no   
1     33.0       services  married  secondary      no   4789.0     yes  yes   
2     35.0     management   single   tertiary      no   1350.0     yes   no   
3     30.0     management  married   tertiary      no      NaN     yes  yes   
4     59.0    blue-collar  married  secondary      no      0.0     yes   no   
...    ...            ...      ...        ...     ...      ...     ...  ...   
4516  33.0       services  married  secondary      no   -333.0     yes   no   
4517  57.0  self-employed  married   tertiary     yes  -3313.0     yes  yes   
4518  57.0     technician  married  secondary      no    295.0      no   no   
4519  28.0    blue-collar  married  secondary      no   1137.0      no   no   
4520  44.0   entrepreneur   single   tertiary      no   1136.0     yes  yes   

       contact   day  month  duration  campaign  pdays  previous poutcome   y  \
0     cellular  19.0     10      79.0       1.0   -1.0       0.0  unknown  no   
1     cellular  11.0      5     220.0       1.0  339.0       4.0  failure  no   
2     cellular  16.0      4     185.0       1.0  330.0       1.0  failure  no   
3          NaN   3.0      6     199.0       4.0   -1.0       0.0  unknown  no   
4          NaN   5.0      5     226.0       1.0   -1.0       0.0  unknown  no   
...        ...   ...    ...       ...       ...    ...       ...      ...  ..   
4516  cellular  30.0      7     329.0       5.0   -1.0       0.0  unknown  no   
4517       NaN   9.0      5     153.0       1.0   -1.0       0.0  unknown  no   
4518  cellular  19.0      8     151.0      11.0   -1.0       0.0  unknown  no   
4519  cellular   6.0      2     129.0       4.0  211.0       3.0    other  no   
4520  cellular   3.0      4     345.0       2.0  249.0       7.0    other  no   

      year  
0     2022  
1     2022  
2     2022  
3     2022  
4     2022  
...    ...  
4516  2022  
4517  2022  
4518  2022  
4519  2022  
4520  2022  

[4521 rows x 18 columns]

>__Task 21__
>
>Select __age__ column as a series and confirm the result by checking its data type

In [154]:
series_a = pd.Series(bank['age'])
series_b= bank[['age']]
type(series_b)

pandas.core.frame.DataFrame

In [155]:
series_b

age
0     30.0
1     33.0
2     35.0
3     30.0
4     59.0
...    ...
4516  33.0
4517  57.0
4518  57.0
4519  28.0
4520  44.0

[4521 rows x 1 columns]

In [148]:
type(series_a)

pandas.core.series.Series

Notice that __`df[...]` returns a series and `df[[...]]` returns a data frame__.

>__Task 22__
>
>Select columns __job__, __education__, and __balance__ as a data frame and confirm the result by checking its data type

In [166]:
df_bank = bank[['job', 'education', 'balance']]
df_bank

job  education  balance
0        unemployed    primary   1787.0
1          services  secondary   4789.0
2        management   tertiary   1350.0
3        management   tertiary      NaN
4       blue-collar  secondary      0.0
...             ...        ...      ...
4516       services  secondary   -333.0
4517  self-employed   tertiary  -3313.0
4518     technician  secondary    295.0
4519    blue-collar  secondary   1137.0
4520   entrepreneur   tertiary   1136.0

[4521 rows x 3 columns]

In [158]:
# Return data type
type(df_bank)

pandas.core.frame.DataFrame

>__Task 23__
>
>Retrieve the last 7 rows and first 5 columns from the __bank__ data

In [171]:
test  = bank[bank.columns[:5]].tail(7)
test

age            job  marital  education default
4514  38.0    blue-collar  married  secondary      no
4515  32.0       services   single  secondary      no
4516  33.0       services  married  secondary      no
4517  57.0  self-employed  married   tertiary     yes
4518  57.0     technician  married  secondary      no
4519  28.0    blue-collar  married  secondary      no
4520  44.0   entrepreneur   single   tertiary      no

### Dates and Times

Let's create a new column of the client contact dates using the __bank__ data:

In [172]:
bank['contact_date'] = bank['year'].astype(str)+'-'+bank['month'].astype(str)+'-'+bank['day'].astype(int).astype(str)
bank['contact_date']

0       2022-10-19
1        2022-5-11
2        2022-4-16
3         2022-6-3
4         2022-5-5
           ...    
4516     2022-7-30
4517      2022-5-9
4518     2022-8-19
4519      2022-2-6
4520      2022-4-3
Name: contact_date, Length: 4521, dtype: object

The last line above shows that the dtype (data type) is a generic object, not a datetime type.

>__Task 24__
>
>Convert the __contact_date__ column to a datetime object

In [180]:
bank['contact_date'] = pd.to_datetime(bank['contact_date'])
bank['contact_date']

0      2022-10-19
1      2022-05-11
2      2022-04-16
3      2022-06-03
4      2022-05-05
          ...    
4516   2022-07-30
4517   2022-05-09
4518   2022-08-19
4519   2022-02-06
4520   2022-04-03
Name: contact_date, Length: 4521, dtype: datetime64[ns]

Now, it is properly read as date.

## Data Manipulation

In [181]:
import warnings
warnings.filterwarnings("ignore")

>__Task 25__
>
>Import the data file "hc_train.csv" and explore the first 5 rows

In [182]:
hc = pd.read_csv('./raw/hc_train.csv')
...

>__Task 26__
>
>Convert the values of the __Department__ column to uppercase

In [189]:
hc['Department'] = hc['Department'].str.upper()
hc['Department']# Display the first few rows of the DataFrame to verify the changes



0                GYNECOLOGY
1                GYNECOLOGY
2                GYNECOLOGY
3                ANESTHESIA
4                GYNECOLOGY
                ...        
51233            GYNECOLOGY
51234            GYNECOLOGY
51235            GYNECOLOGY
51236            GYNECOLOGY
51237    TB & CHEST DISEASE
Name: Department, Length: 51238, dtype: object

### Replace Values

>__Task 27__
>
>Replace `TB & Chest disease` in the __Department__ column with `Tuberculosis & Chest`

In [193]:
# Assuming your DataFrame is named 'df'
hc['Department'] = hc[['Department']].replace(('TB & Chest disease').upper(), ('Tuberculosis & Chest').upper())

# Print unique variables in the column to confirm the change 
hc['Department'].unique()

array(['GYNECOLOGY', 'ANESTHESIA', 'RADIOTHERAPY', 'SURGERY',
       'TUBERCULOSIS & CHEST'], dtype=object)

In [194]:
hc

Unnamed: 0  case_id  Hospital_code Hospital_type_code  \
0          119967   119968             27                  a   
1           92433    92434              6                  a   
2          132258   132259             16                  c   
3          168439   168440             23                  a   
4           82100    82101             25                  e   
...           ...      ...            ...                ...   
51233      289419   289420             10                  e   
51234      285283   285284             11                  b   
51235       79117    79118              9                  d   
51236      128901   128902             23                  a   
51237      210970   210971              2                  c   

       City_Code_Hospital Hospital_region_code  \
0                       7                    Y   
1                       6                    X   
2                       3                    Z   
3                       6                    X   
4                       1                    X   
...                   ...                  ...   
51233                   1                    X   
51234                   2                    Y   
51235                   5                    Z   
51236                   6                    X   
51237                   5                    Z   

       Available Extra Rooms in Hospital            Department Ward_Type  \
0                                      3            GYNECOLOGY         R   
1                                      4            GYNECOLOGY         Q   
2                                      4            GYNECOLOGY         S   
3                                      2            ANESTHESIA         S   
4                                      3            GYNECOLOGY         R   
...                                  ...                   ...       ...   
51233                                  3            GYNECOLOGY         Q   
51234                                  4            GYNECOLOGY         Q   
51235                                  3            GYNECOLOGY         S   
51236                                  4            GYNECOLOGY         R   
51237                                  2  TUBERCULOSIS & CHEST         S   

      Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0                      C        2.0      11389                8.0   
1                      F        1.0      12522                2.0   
2                      A        3.0     119556                8.0   
3                      F        3.0     107177                8.0   
4                      E        3.0      64508               13.0   
...                  ...        ...        ...                ...   
51233                  E        4.0      84995                8.0   
51234                  D        2.0      27052                8.0   
51235                  F        3.0     109756                5.0   
51236                  F        4.0      35479               12.0   
51237                  F        2.0      99310                9.0   

      Type of Admission Severity of Illness  Visitors with Patient    Age  \
0             Emergency               Minor                      2  11-20   
1             Emergency             Extreme                      4  31-40   
2                Trauma            Moderate                      6  71-80   
3                Urgent             Extreme                      2  71-80   
4                Trauma            Moderate                      3  61-70   
...                 ...                 ...                    ...    ...   
51233            Trauma               Minor                      2  21-30   
51234         Emergency            Moderate                      2  51-60   
51235         Emergency            Moderate                     10  51-60   
51236            Trauma               Minor                      2  21-30   
51237            Trauma             Extreme     

We can also replace with different values by passing a list or dict as substitutes.

>__Task 28__
>
>Replace values in the __Severity of Illness__ column with a dictionary that maps variables below:
>
>- Extreme: '3rd degree'
>- Moderate: '2nd degree'
>- Minor: '1st degree'

In [197]:
# Creat a dict
map_dict = {'Extreme': '3rd degree',
'Moderate': '2nd degree',
'Minor': '1st degree'}
# Replace values with the dict

hc['Severity of Illness degrees'] = hc['Severity of Illness'].map(map_dict)
hc


Unnamed: 0  case_id  Hospital_code Hospital_type_code  \
0          119967   119968             27                  a   
1           92433    92434              6                  a   
2          132258   132259             16                  c   
3          168439   168440             23                  a   
4           82100    82101             25                  e   
...           ...      ...            ...                ...   
51233      289419   289420             10                  e   
51234      285283   285284             11                  b   
51235       79117    79118              9                  d   
51236      128901   128902             23                  a   
51237      210970   210971              2                  c   

       City_Code_Hospital Hospital_region_code  \
0                       7                    Y   
1                       6                    X   
2                       3                    Z   
3                       6                    X   
4                       1                    X   
...                   ...                  ...   
51233                   1                    X   
51234                   2                    Y   
51235                   5                    Z   
51236                   6                    X   
51237                   5                    Z   

       Available Extra Rooms in Hospital            Department Ward_Type  \
0                                      3            GYNECOLOGY         R   
1                                      4            GYNECOLOGY         Q   
2                                      4            GYNECOLOGY         S   
3                                      2            ANESTHESIA         S   
4                                      3            GYNECOLOGY         R   
...                                  ...                   ...       ...   
51233                                  3            GYNECOLOGY         Q   
51234                                  4            GYNECOLOGY         Q   
51235                                  3            GYNECOLOGY         S   
51236                                  4            GYNECOLOGY         R   
51237                                  2  TUBERCULOSIS & CHEST         S   

      Ward_Facility_Code  Bed Grade  patientid  City_Code_Patient  \
0                      C        2.0      11389                8.0   
1                      F        1.0      12522                2.0   
2                      A        3.0     119556                8.0   
3                      F        3.0     107177                8.0   
4                      E        3.0      64508               13.0   
...                  ...        ...        ...                ...   
51233                  E        4.0      84995                8.0   
51234                  D        2.0      27052                8.0   
51235                  F        3.0     109756                5.0   
51236                  F        4.0      35479               12.0   
51237                  F        2.0      99310                9.0   

      Type of Admission Severity of Illness  Visitors with Patient    Age  \
0             Emergency               Minor                      2  11-20   
1             Emergency             Extreme                      4  31-40   
2                Trauma            Moderate                      6  71-80   
3                Urgent             Extreme                      2  71-80   
4                Trauma            Moderate                      3  61-70   
...                 ...                 ...                    ...    ...   
51233            Trauma               Minor                      2  21-30   
51234         Emergency            Moderate                      2  51-60   
51235         Emergency            Moderate                     10  51-60   
51236            Trauma               Minor                      2  21-30   
51237            Trauma             Extreme     

### Rename Column and Row Labels

>__Task 29__
>
>Rename all column headings to their lowercase values by passing a `str` function

In [199]:
# For example, to convert all column names to lowercase
hc = hc.rename(columns=str.lower)

hc


unnamed: 0  case_id  hospital_code hospital_type_code  \
0          119967   119968             27                  a   
1           92433    92434              6                  a   
2          132258   132259             16                  c   
3          168439   168440             23                  a   
4           82100    82101             25                  e   
...           ...      ...            ...                ...   
51233      289419   289420             10                  e   
51234      285283   285284             11                  b   
51235       79117    79118              9                  d   
51236      128901   128902             23                  a   
51237      210970   210971              2                  c   

       city_code_hospital hospital_region_code  \
0                       7                    Y   
1                       6                    X   
2                       3                    Z   
3                       6                    X   
4                       1                    X   
...                   ...                  ...   
51233                   1                    X   
51234                   2                    Y   
51235                   5                    Z   
51236                   6                    X   
51237                   5                    Z   

       available extra rooms in hospital            department ward_type  \
0                                      3            GYNECOLOGY         R   
1                                      4            GYNECOLOGY         Q   
2                                      4            GYNECOLOGY         S   
3                                      2            ANESTHESIA         S   
4                                      3            GYNECOLOGY         R   
...                                  ...                   ...       ...   
51233                                  3            GYNECOLOGY         Q   
51234                                  4            GYNECOLOGY         Q   
51235                                  3            GYNECOLOGY         S   
51236                                  4            GYNECOLOGY         R   
51237                                  2  TUBERCULOSIS & CHEST         S   

      ward_facility_code  bed grade  patientid  city_code_patient  \
0                      C        2.0      11389                8.0   
1                      F        1.0      12522                2.0   
2                      A        3.0     119556                8.0   
3                      F        3.0     107177                8.0   
4                      E        3.0      64508               13.0   
...                  ...        ...        ...                ...   
51233                  E        4.0      84995                8.0   
51234                  D        2.0      27052                8.0   
51235                  F        3.0     109756                5.0   
51236                  F        4.0      35479               12.0   
51237                  F        2.0      99310                9.0   

      type of admission severity of illness  visitors with patient    age  \
0             Emergency               Minor                      2  11-20   
1             Emergency             Extreme                      4  31-40   
2                Trauma            Moderate                      6  71-80   
3                Urgent             Extreme                      2  71-80   
4                Trauma            Moderate                      3  61-70   
...                 ...                 ...                    ...    ...   
51233            Trauma               Minor                      2  21-30   
51234         Emergency            Moderate                      2  51-60   
51235         Emergency            Moderate                     10  51-60   
51236            Trauma               Minor                      2  21-30   
51237            Trauma             Extreme     

>__Task 30__
>
>Rename the column headings below using a dictionary that maps
>
>- `Severity of Illness` to `Severity`
>- `case_id` to `ID`

In [204]:
col_dict = {'severity of illness': 'Severity',
            'case_id': 'ID'}
hc.rename(columns=col_dict, inplace=True )
hc.head()

unnamed: 0      ID  hospital_code hospital_type_code  city_code_hospital  \
0      119967  119968             27                  a                   7   
1       92433   92434              6                  a                   6   
2      132258  132259             16                  c                   3   
3      168439  168440             23                  a                   6   
4       82100   82101             25                  e                   1   

  hospital_region_code  available extra rooms in hospital  department  \
0                    Y                                  3  GYNECOLOGY   
1                    X                                  4  GYNECOLOGY   
2                    Z                                  4  GYNECOLOGY   
3                    X                                  2  ANESTHESIA   
4                    X                                  3  GYNECOLOGY   

  ward_type ward_facility_code  bed grade  patientid  city_code_patient  \
0         R                  C        2.0      11389                8.0   
1         Q                  F        1.0      12522                2.0   
2         S                  A        3.0     119556                8.0   
3         S                  F        3.0     107177                8.0   
4         R                  E        3.0      64508               13.0   

  type of admission  Severity  visitors with patient    age  \
0         Emergency     Minor                      2  11-20   
1         Emergency   Extreme                      4  31-40   
2            Trauma  Moderate                      6  71-80   
3            Urgent   Extreme                      2  71-80   
4            Trauma  Moderate                      3  61-70   

   admission_deposit                stay severity of illness degrees  
0             5072.0               21-30                  1st degree  
1             3585.0               21-30                  3rd degree  
2             4013.0  More than 100 Days                  2nd degree  
3             5160.0               21-30                  3rd degree  
4             4099.0               21-30                  2nd degree

### Binning Methods

>__Task 31__
>
>Group the case IDs into three categories below:
>
>- (0, 100000) to `old case`
>- (100001-200000) to `recent case`
>- (200001-last) to `new case`

In [206]:
# Check the maximum value of the column
hc['ID'].max()

318438

In [210]:
bin = [0, 100000, 200000, 10000000]
group =  pd.cut(hc['ID'], bins=bin)
group

0          (100000, 200000]
1               (0, 100000]
2          (100000, 200000]
3          (100000, 200000]
4               (0, 100000]
                ...        
51233    (200000, 10000000]
51234    (200000, 10000000]
51235           (0, 100000]
51236      (100000, 200000]
51237    (200000, 10000000]
Name: ID, Length: 51238, dtype: category
Categories (3, interval[int64, right]): [(0, 100000] < (100000, 200000] < (200000, 10000000]]

>__Task 32__
>
>Group the case IDs into to 3 equal-sized bins with 4 decimal places

In [212]:
group_equ = pd.cut(hc['ID'], 3, precision= 4)
group_equ

0        (106146.6667, 212292.3333]
1           (-317.437, 106146.6667]
2        (106146.6667, 212292.3333]
3        (106146.6667, 212292.3333]
4           (-317.437, 106146.6667]
                    ...            
51233       (212292.3333, 318438.0]
51234       (212292.3333, 318438.0]
51235       (-317.437, 106146.6667]
51236    (106146.6667, 212292.3333]
51237    (106146.6667, 212292.3333]
Name: ID, Length: 51238, dtype: category
Categories (3, interval[float64, right]): [(-317.437, 106146.6667] < (106146.6667, 212292.3333] < (212292.3333, 318438.0]]

>__Task 33__
>
>Group the case IDs into 4 quartiles with 2 decimal places

In [213]:
group_qua = pd.qcut(hc['ID'], 4, precision= 2)
group_qua

0        (79834.25, 159728.5]
1        (79834.25, 159728.5]
2        (79834.25, 159728.5]
3        (159728.5, 238968.5]
4        (79834.25, 159728.5]
                 ...         
51233    (238968.5, 318438.0]
51234    (238968.5, 318438.0]
51235        (0.99, 79834.25]
51236    (79834.25, 159728.5]
51237    (159728.5, 238968.5]
Name: ID, Length: 51238, dtype: category
Categories (4, interval[float64, right]): [(0.99, 79834.25] < (79834.25, 159728.5] < (159728.5, 238968.5] < (238968.5, 318438.0]]

### Random Sampling

>__Task 34__
>
>Randomly select 10 data points from the __hc__ data without repeat elements

In [215]:
hc.sample(10, replace=False)

unnamed: 0      ID  hospital_code hospital_type_code  \
89         251220  251221              7                  a   
16712      256358  256359             27                  a   
16567       33750   33751             23                  a   
34077      135380  135381             15                  c   
25923      161018  161019             28                  b   
34570      265385  265386              3                  c   
5038       195640  195641             27                  a   
35551       28597   28598             26                  b   
29181      149018  149019              1                  d   
33727      130867  130868             17                  e   

       city_code_hospital hospital_region_code  \
89                      4                    X   
16712                   7                    Y   
16567                   6                    X   
34077                   5                    Z   
25923                  11                    X   
34570                   3                    Z   
5038                    7                    Y   
35551                   2                    Y   
29181                  10                    Y   
33727                   1                    X   

       available extra rooms in hospital            department ward_type  \
89                                     2            GYNECOLOGY         R   
16712                                  3            GYNECOLOGY         R   
16567                                  3          RADIOTHERAPY         R   
34077                                  4            ANESTHESIA         Q   
25923                                  2            GYNECOLOGY         R   
34570                                  4            GYNECOLOGY         R   
5038                                   3            GYNECOLOGY         R   
35551                                  4            GYNECOLOGY         Q   
29181                                  2  TUBERCULOSIS & CHEST         S   
33727                                  4            GYNECOLOGY         R   

      ward_facility_code  bed grade  patientid  city_code_patient  \
89                     F        2.0      80244                NaN   
16712                  C        2.0      28221                7.0   
16567                  F        2.0      96322                1.0   
34077                  F        4.0     123497               24.0   
25923                  F        3.0      13152                1.0   
34570                  A        2.0      98030                6.0   
5038                   C        3.0      10349                8.0   
35551                  D        2.0      39804                2.0   
29181                  B        2.0      60085                8.0   
33727                  E        4.0      76406               31.0   

      type of admission  Severity  visitors with patient    age  \
89            Emergency     Minor                      2  51-60   
16712            Trauma  Moderate                      3  61-70   
16567         Emergency     Minor                      2  71-80   
34077         Emergency  Moderate                      2  51-60   
25923            Trauma  Moderate                      2  61-70   
34570            Trauma  Moderate                      3  71-80   
5038             Trauma  Moderate                      2  31-40   
35551            Trauma  Moderate                      4  51-60   
29181         Emergency   Extreme                      2  61-70   
33727            Trauma  Moderate                      2  51-60   

       admission_deposit   stay severity of illness degrees  
89                7931.0  11-20                  1st degree  
16712             4386.0  11-20                  2nd degree  
16567             4161.0   0-10                  1st degree  
34077             6271.0  11-20                  2nd degree  
25923             4778.0  11-20                  2nd degree  
34570             4997.0  11-20                  2nd de

>__Task 35__
>
>Randomly select 50 data points from the __patientid__ column allowing repeat elements

In [216]:
hc.sample(50, replace = True)

unnamed: 0      ID  hospital_code hospital_type_code  \
42056      110783  110784             27                  a   
46319      283355  283356              6                  a   
35147       38481   38482             10                  e   
18385      256342  256343             26                  b   
30160      105614  105615              6                  a   
33865       21190   21191             27                  a   
4775       149120  149121             23                  a   
46034      247244  247245             19                  a   
25410       71501   71502             18                  d   
35322      101733  101734             11                  b   
13430       63607   63608             32                  f   
329        215536  215537             10                  e   
39927      215343  215344             13                  a   
401        123537  123538             17                  e   
3933       311646  311647             26                  b   
923        229706  229707             32                  f   
34775      311834  311835              5                  a   
444         72442   72443             26                  b   
14735      109683  109684              3                  c   
1234        19199   19200             14                  a   
8565       237518  237519             29                  a   
24416      258974  258975             12                  a   
16709      176096  176097             25                  e   
38048       53189   53190              2                  c   
49482        7627    7628              7                  a   
4427       177774  177775             12                  a   
13997       37649   37650             23                  a   
32260      209787  209788             26                  b   
44799      237256  237257             29                  a   
44873       47489   47490              1                  d   
12922       43083   43084             32                  f   
26632      117670  117671             11                  b   
42927      133851  133852             23                  a   
3576        94154   94155             14                  a   
42898       44233   44234             19                  a   
42210       10246   10247              1                  d   
15295      219449  219450             23                  a   
47384      297346  297347             23                  a   
50553      196723  196724             25                  e   
10477       75616   75617             21                  c   
1567       215698  215699             32                  f   
12858      275981  275982             26                  b   
21135      187331  187332             27                  a   
20507      233596  233597             23                  a   
21243      315573  315574             26                  b   
42105      173500  173501             13                  a   
25788      152854  152855             11                  b   
7038        75433   75434             14                  a   
4502       128237  128238             13                  a   
47765      161352  161353             28                  b   

       city_code_hospital hospital_region_code  \
42056                   7                    Y   
46319                   6                    X   
35147                   1                    X   
18385                   2                    Y   
30160                   6                    X   
33865                   7                    Y   
4775                    6                    X   
46034                   7                    Y   
25410                  13                    Y   
35322                   2                    Y   
13430                   9                    Y   
329                     1                    X   
39927                   5                    Z   
401                     1                    X   
3933                    2                  